### ISSUE TITLE
dontShowAgain don't work

### ISSUE THREAD

**Issue by Kalarumeth** [usablica/intro.js#1683]
Hi,
I try to implement your service on my site, on IntroJs documentation I find dontShowAgain I tried to add this on options and nothing change, the field to click does not appear and cookie doesn't generate. I tried to use introJs().setDontShowAgain(true); and feedback is TypeError: .....is not a function. I would like it once the tutorial is finished or skipped was generated a cookie to block automatic execution.

Do you have any indications to resolve or the correct functioning of dontShawAgain?
If there isn't solution, could you tell me the event of the skip button and I catch it to generate cookie.

Thanks in advance, have a good day.

**Comment by Kalarumeth** [comment]
For made correctly work of Cookie, I make a workaround on my site with Js-Cookie, I set before start IntroJS a controller for cookie and if isn't eq Complete make run Intro and on IntroJs option I add in onExit Cookie set Complete.
There isn't the right way but it works so well.

**Comment by afshinm** [comment]
The "Don't Show Again" checkbox should appear on all steps of the tour, see https://github.com/usablica/intro.js/blob/edcd7a06683dd2ebe1422b4b76f667cb9631e075/src/core/showElement.js#L361-L381 

We also have this test here https://github.com/usablica/intro.js/blob/b9e1390e6fa3014f616564ee8d9dc43b36692d67/tests/cypress/e2e/tour/dont-show-again.cy.js#L37-L71, which is basically testing that:
 1- You start the tour
 2- Check the "Don't show again" checkbox"
 3- Exit the tour
 4- `start()` should not open the tour again because the cookie exists, etc.

**Comment by Dwjem** [comment]
> 你好。我有一个与“dontShowAgain”功能相关的问题。
> 
> 这是我在旅途中的配置：
> 
> ```js
> const defaultTourOptions: Options = {
>   showProgress: false,
>   showBullets: false,
>   exitOnEsc: false,
>   exitOnOverlayClick: false,
>   keyboardNavigation: false,
>   dontShowAgain: true,
>   dontShowAgainLabel: "Don't show this again",
>   dontShowAgainCookie: "introjs-dontShowAgain-loginTour",
>   dontShowAgainCookieDays: 365,
>   steps: [
>    // ... some steps here...
>   ]
> };
> ```
> 
> 复选框或字段出现在游览的每个步骤中。我想象这个复选框只会出现在游览的最后一步。有没有办法让复选框只出现在游览的最后一步？
> 
> 此外，如果我使用，则 cookie 在浏览器上设置正确`.setDontShowAgain(true)`，但如果页面刷新，则游览开始。这是预期的行为？

I also encountered the same problem, how did you solve it?
