### ISSUE TITLE
Bootstrap 3 modal conflict

### ISSUE THREAD

**Issue by S7sRuss** [usablica/intro.js#216]
No element inside Bootstrap 3 modal appears after calling intro.js start. Can be it a problem with z-index delegation?

Printscreen: ![capture](https://f.cloud.github.com/assets/711171/1391989/e3d6607e-3c04-11e3-8407-7f17ba1df883.PNG)

**Comment by silentFred** [comment]
Hey @ryan-schroeder would you mind elaborating on what you did to fix it? Thanks!

**Comment by ryan-schroeder** [comment]
@silentFred Ooooh sorry man, I really don't remember  =(.  Re-reading my comment, it is pretty vague - I think I needed to remove the css attribute "position: fixed" from something in order to fix it (probably "position" instead of "display", that was probably a typeo).  I * think * that the "fixed" css was on a part of my site (as opposed to being part of the intro.js code).  I think the element with the "fixed" css was a parent of the element I wanted to highlight  ("targetElement").

Best of luck, sorry for not being more help!

**Comment by cheiff** [comment]
Hi, 
I have solved this by adding the following extra CSS:
```css
.introjs-fixParent, #mydiv.introjs-fixParent {
  position: inherit;
}
```
It shifts some divs a little bit, but once the walkthrough is finished, not any more.
Hope this helps.

**Comment by thaovi0308** [comment]
I tried this and succeeded
.introjs-fixParent {
            z-index: 9999999 !important;
        }

**Comment by michalhudecek** [comment]
@thaovi0308 This helps but only partially. Now the whole modal is always visible even when the target element fo introjs is only a button inside the modal

@cheiff This also worked but moved the modal down below screen fold

I finally fixed it with this code:

``` css
.introjs-fixParent, #modal--composer.introjs-fixParent {
  position: absolute;
}
```

**Comment by alessandromontividiu03** [comment]
Hi, if you are using bootstrap, try this:

.modal { z-index: 100000000000000000000 !important; }
.introjs-fixedTooltip { z-index: 200000000000000000000 !important; }
