### ISSUE TITLE
Steps for the new elements (from the javascript dynamic DOM)

### ISSUE THREAD

**Issue by mdtrooper** [usablica/intro.js#314]
I have a code that write by javascript new elements, but I have too the steps write into a array hash "steps" with the new elements.

And when it runs the bubble dialog does not hook to the new elements (makes with javascript).

**Comment by elwirra** [comment]
I have the same problem. When introjs starts, to my DOM there are added elements (and I rather can't change that, because they are interactive - added by user, and introjs shows this functionality) and introjs can't see them. Can't find out how to workaround this problem. Here is jsfiddle demonstrating this scenario:

https://jsfiddle.net/3ocyuu65/31/

**Comment by martinmicunda** [comment]
Is there any update on this solution?

**Comment by martinmicunda** [comment]
@elwirra have you found workaround?

**Comment by citiconsultants** [comment]
@martinmicunda @elwirra  - Have you found a workaround? 

To solve the problem - I am doing like so: (it is a very ugly solution - but it works)

In the fiddle example - add a check to see if a certain step has been reached and then exit and restart the intro to get there.

eg: 
` i = 0;
introProfile.onafterchange(function(targetElement) {
    var nextSteper = this._currentStep + 1;
    if ($(targetElement).attr('id') == "intro_step6" && i < 1){
    	i++;
    	introProfile.exit().start().goToStep(nextSteper);
    }
});`


As I said - this works but is not elegant!

**Comment by Stiveknx** [comment]
For those who are interested...
I'm Using this workaround:

Working fine ...
https://github.com/usablica/intro.js/issues/328#issuecomment-107231869
