### ISSUE TITLE
Steps doesn't start propertly when doing multi page intro

### ISSUE THREAD

**Issue by Drintios** [usablica/intro.js#416]
When i do a multi page intro, in the second page steps gets weird. It start fine with the step defined on the data-step property, but when i click next, the text layout disappears and trows this console error = "
  oldReferenceLayer.querySelector() is null" i found a work around but before i submit it i want to know if there is a much simpler way to fix this.

PS: sorry for my english, it's my second language ^^

**Comment by Brammz** [comment]
Hey man, I have the same problem, what's your workaround? And have you found a better solution already ?

**Comment by jdgarrido** [comment]
@Drintios @Brammz i have a solution, but this is no the best way for do this.

the problem is because the bullets on the modal with the button for next and prev lose the active class, then, i add the following

<script>
  $(document).ready(function(){
    if (RegExp('tour', 'gi').test(window.location.search)) {
      introJs().setOption('doneLabel', 'Next page').start().oncomplete(function() {
        window.location.href = '/demo/1/stage1?tour=true';
      });
      $('.introjs-bullets li a')[0].className = 'active'; //this line add to the first element the active class
    }
  })
</script>

that's all.
i hope works for you
saludos
