### ISSUE TITLE
oncomplete does not work if you press enter on finish button

### ISSUE THREAD

**Issue by hossein-nasr** [usablica/intro.js#422]
on line 216 at function self._onKeyDown you need to call oncomplete i think.(or any better place that you may know).

**Comment by yuvale** [comment]
Same as #366.

**Comment by jonnymaceachern** [comment]
Spent an hour wondering what was wrong with my syntax. Thanks @hoossseinut.

**Comment by Maado** [comment]
Check my pull request 
https://github.com/usablica/intro.js/pull/439

**Comment by CodyFitzpatrick** [comment]
I also continue to have this problem despite @afshinm saying it was fixed in #366. In that issue, there is a codepen which still illustrates the problem.

In summary: if you use your enter/return key to complete the tour, onComplete is _not_ called. If you click the "Done" button, onComplete _is_ called. While this is a minor issue, it can cause events we want to fire once the tour to complete to _not_ fire (although, from the user's perspective, all is well, because the tour was closed/hidden).
