### ISSUE TITLE
Custom CSS classes for all generated elements

### ISSUE THREAD

**Issue by andyblount** [usablica/intro.js#429]
It would be useful to be able to add custom CSS classes for all generated elements, not just the TooltipClass and HighlightClass. I'm mainly thinking buttons but any generated element type should be included for completeness. This is useful when integrating with existing project style sheets or frameworks such as Bootstrap.

**Comment by raduluchian** [comment]
I completely agree with this. We want to use it as part our SPA and it would be great if we could specify custom classes for all elements so that they would automatically get the styles from our own custom framework (we already have classes for tooltips, buttons and so on).

The plugin could have a set of default classes applied but overwrite them if the developer explicitly specifies different classes.
