### ISSUE TITLE
Event onafterchange has generated before end of animation

### ISSUE THREAD

**Issue by rugooner** [usablica/intro.js#430]
Feature or Bug?

**Comment by isuftin** [comment]
I see this as a bug. I am having some very difficult issues with this and onbeforechange. The problem is that onbeforechange gets called in the code and does not wait for a resolution of that before calling the next step. This is an issue because with some parts of the intro I need to animate an element to get into position before I can have the intro attach to its element. The end result is that the intro element goes off to the top left of the page and the intro is effectively broken at that point.

IntroJS is written in a very protected way so there is no way to overrode the _nextStep call or have it wait for a timed event to finish before executing.

**Comment by afshinm** [comment]
I will address this one for the next version.
