### ISSUE TITLE
Click , Focus , Type in class or id or any object

### ISSUE THREAD

**Issue by Global90** [usablica/intro.js#440]
please add Click , Focus , Type in class or id or any object

**Comment by Maado** [comment]
can you explain more please ?!

**Comment by krngrvr09** [comment]
I am assuming you want to define ``clicking of an element``, ``insert some text in a textbox``, as attributes  in the IntroJs itself.

You can do these things in the ``onbeforechange``,``onafterchange`` callbacks.

Let me know if wrongly understood your request.

**Comment by Maado** [comment]
might be he want a callback for each step . not for whole the intro

**Comment by AntoineWtrnd** [comment]
@krngrvr09, you can't use Focus(); of jQuery using onafterchange since this call back is not really called on after the change. The callback is called before the tooltips fully appear, so you can't focus anything.

**You just, can't at all using IntroJS.** 

The only way was onafterchange but not working.

I suggest you to use Bootstrap Tour.

IntroJS have alot of bug and developer ignore it.
