### ISSUE TITLE
Navigate backwards in a multi-page intro tour

### ISSUE THREAD

**Issue by devfordays** [usablica/intro.js#472]
Greetings! 
Thank you very much for this beautiful plugin.
Is there a way to navigate backwards in a mutiple-page intro? I would like to give the user this freedom, in case they want to see something again from a previous page!

Thanks.
Alex

**Comment by ZaLiTHkA** [comment]
Checking the [source](view-source:http://usablica.github.io/intro.js/example/multi-page/second.html?multipage=true) for the multi-page example, the tour on the second page is only triggered because of the `multipage` URL parameter. The move from the first page to the second is achieved by the following:

```
introJs().setOption('doneLabel', 'Next page').start().oncomplete(function() {
  window.location.href = 'second.html?multipage=true';
});
```

In fact, the redirect URL doesn't even need `second.html?multipage=true`, simple using `second.html?multipage` is enough since the check on page 2 only looks for the existence of the string `multipage`.

So in this case, going "back" to the first page from the second would be a two step process:

**On the first page**, include a check to see if the page was loaded from the tour or not. So, using the same URL parameter trick:

```
if (RegExp('resume', 'gi').test(window.location.search)) {
  introJs().start();
}
```

**On the second page** create the "Previous Page" link. Such as:

```
introJs().setOption('doneLabel', 'Previous page').start().oncomplete(function() {
  window.location.href = 'first.html?resume';
});
```

It's important to note that this isn't handled by the tour plugin directly, but rather by some crafty JS that spawns the tour as defined on the current page. So unless you write some fancy "target step" switch statement based on a parameter and it's value, you won't be able to "step back" from the first step on page 2 straight to the last step on page 1. In each case, the page will load *and then* the current page tour will start.

Depending on how important this functionality is, I could write a simple wrapper that will allow you to step back and forth across pages and possibly even jump straight from one page to a specific step in another page. Let me know if you need something like this and I'll do my best to help.

**Comment by ericenns** [comment]
@ZaLiTHkA that is one way to do it, but unfortunately doesn't work when your tour is greater than 2 pages

**Comment by ZaLiTHkA** [comment]
@ericenns, that's actually a good point. And, in that context, my suggestion above would simply cause the tours to loop: going page 1 > page 2 > page 1 > page 2, etc.. :/

The only other idea I can think of would be to add custom buttons to the tour dialogs. Looks like the only buttons at the moment are `next`, `prev`, `skip` and `done`.

It would be nice to be able to specify additional buttons in an array inside the tour step. I'm imagining something like:

```
{
  steps: [
    {
      intro: "On this page you see a little girl giggling at a hippopotamus. I wonder why?",
      buttons: [
        {
          label: "Goto page 3",
          url: "/page3.html?tour=continue"
        },
        {
          label: "...",
          url: "..."
        }
      ]
    }
  ]
}
```

The real tricky part with this would be where to place them in the dialog itself. Maybe an extra row above the standard buttons? Either way, something like this would give the existing functionality a much greater playground in which to work.

**Comment by ericenns** [comment]
Would you want the 'Previous Page' button to only show on the first popup of a page. If so I have an idea for that. Also should the button take you to the last popup of the tour on the previous page.

**Comment by ZaLiTHkA** [comment]
I think that would be up to @anp6vq, but I think my idea of adding custom buttons to specific tour steps would take care of that particular requirement.

**Comment by ArjunAroraDA** [comment]
Any update on @ericenns point? As i need to navigate to previous page and at last pop up from the next page first pop up.
