### ISSUE TITLE
Commercially use introjs version 2.0 from before new licenses?

### ISSUE THREAD

**Issue by NhatHo** [usablica/intro.js#573]
Hello,

As stated in the title, I'm using intro.js from Feb, 2016 (MIT license), can I still use this version of intro.js (not updating) for commercial purposes? How would these new licenses influence the older versions?

**Comment by Tea23** [comment]
Since it's MIT licensed there's no need to purchase a commercial license anyway. You can use any version of this, commercially or not and it's totally fine. You can use the current version or the previous one commercially.

I'm not entirely sure why there is a separate 'commercial license'. If I was hosting a commercial project, I don't know what compels me to pay for a license.

**Comment by afshinm** [comment]
Guys, that's fine to use Intro.js < v2.0.0 without the commercial license.

**Comment by Tea23** [comment]
It's also fine to use 2.1 without a commercial license though, because it's under MIT. For what purpose would I *require* a commercial license?

**Comment by afshinm** [comment]
You would need a commercial licence if you are using the project for commercial projects (apps, themes, plugins, etc.). otherwise, it's okay to use it for personal and open-source projects.

**Comment by Tea23** [comment]
But the MIT license says I'm free to use the software for any purpose. So if someone incorporates it into a commercial project without paying you for a commercial license, there's actually nothing wrong with that, according to the terms of the MIT.

What does paying for a commercial license get me?

**Comment by NhatHo** [comment]
My question is that the version I'm using is 2.0.0, but I have been using it since before license change, that's why I'm confused. I understand that under MIT the library is free to use for whatever purpose.

**Comment by atifsyedali** [comment]
Same boat here. There was no commercial license until recently, and as a matter of fact the version 2.0.0 did not have the commercial license.

The other problem is with the conflict with the MIT license. @afshinm If you really want a commercial license for this, then you should change any UPCOMING version's license to:

1. AGPL
2. Commercial license

However, all current code is still MIT licensed, and you cannot change it to commercial.

**Comment by afshinm** [comment]
The software is still under MIT license but with a condition. It's MIT for personal and open-source usages and I released the version 2.0 under the commercial license. 

- https://en.wikipedia.org/wiki/Multi-licensing
- http://oss-watch.ac.uk/resources/duallicence2

**Comment by afshinm** [comment]
@NhatHo right, you can still use the library if you are using < v2.0. otherwise, you need to obtain a commercial license.

**Comment by NhatHo** [comment]
@afshinm Just to confirm to be sure. Since I'm using version 2.0.0 even though I got it before license change, I still need to purchase commercial license for commercial usage? Please confirm this so I can make decision accordingly.

**Comment by afshinm** [comment]
@NhatHo Yes, in this case, you would need a commercial license. (however, I updated the README after releasing v2.0.0).

Let me clarify that I added commercial license after v2.0.0 to provide better support for the project. I don't like to leave the project since it's getting more and more popular and of course, as a human, I need to eat :-)

**Comment by atifsyedali** [comment]
@afshinm 

So technically, we can still use the project version <= 2.0.0 (Note the smaller or equal) for commercial purposes based off the MIT license, because at the time of 2.0.0 release there was no commercial license.

**Comment by afshinm** [comment]
@atifsyedali Excuse me Sir but I don't exactly get what you are trying to mention, however, lmk if the following sentence does not seem clear to you:

**Comment by afshinm** [comment]
@atifsyedali and no, there was a commercial license when I released v2.0.0.

**Comment by Tea23** [comment]
I don't take any issue with the project being monetised and I think it's admirable that you have found a way to do it.

However, MIT is the wrong license to choose if you wish to do this. The permissive nature of the license means that even if YOU state in a secondary license that a commercial project cannot make use of it without paying for a license, they still can. Other than compassion, there is nothing to compel users to pay for a license.

AGPL is probably a better fit as it allows for license exceptions to be sold, so you can actually *demand* that a license is paid for in order for intro.js to be included into a proprietary project. You can incentivise this in the way you already do, by offering priority support and all the rest of it. You'll see this practice is used in commercial Linux distributions such as Red Hat, and even Ubuntu has a commercial support option of a similar type.

I'm really sorry that license litigation is a thing and to point it out like this, but I'm just concerned for your business model and I think relicensing at this point would be a good move to ensure your revenue stream.

At the moment the MIT license just leaves a massive gaping hole in your monetisation scheme.

You should be able to relicense to AGPL without much of a problem. GPL is also an option, but AGPL will compel non-commercial projects (who do not purchase your license exception) to contribute code back to you.

**Comment by bobzer** [comment]
Legally you can't change a license after the release so I would think that
v2.0.0 is without commercial license

**Comment by atifsyedali** [comment]
@afshinm The 2.0.0 zip on the Releases page does not have a commercial license in the README or anywhere else.

**Comment by niftylettuce** [comment]
It's still MIT as far as I'm concerned, otherwise if licensing changes or if you want to take people's money, be really consistent everywhere.  Go ahead and git force push a change across all tagged versions, and every commit here.  I can simply republish this as IntroJSMIT and anyone can use.  This is GitHub, it's open source world, keep it one way or the other and stop confusing people into paying you!

**Comment by afshinm** [comment]
@niftylettuce very true. I'm going to change and apply the new license for the next version. 

Again, I did mention on the README that it's not MIT for commercial products. 

The whole point of making the Intro.js dual license is to devote more time to it. No hard feelings, Sir. I'm pretty sure you guys can understand what I'm talking about. To appreciate your help, I promise to add more innovating features and release more versions. 

Last but not least, I really enjoy spending time for all of you. I'd like to save other's time, avoid repeating and that's why I'm contributing and making open-source things.

**Comment by niftylettuce** [comment]
I published an MIT version here if anyone needs it https://github.com/niftylettuce/introjsmit - @afshinm I think you would make more money with projects as opposed to licensing fees.  It is really bad practice and non-standard to ask for license fees for things you put on GitHub. 😦

**Comment by afshinm** [comment]
Just to clarify this thread guys:

I made Intro.js dual license since v2.0 but I didn't change the open-source license to GPL/AGPL and it was my mistake. I will update the license again for the next version.

The whole point of making the Intro.js dual license is to devote more time to it. To appreciate your help, I promise to add more innovating features and release more versions.

Please excuse me for this confusion and I'm pretty sure you will love the new changes.
