### ISSUE TITLE
Increase size of data hint

### ISSUE THREAD

**Issue by fcpauldiaz** [usablica/intro.js#575]
How can I increase the size of the circle in the hint option?

**Comment by bozdoz** [comment]
There is not an easy way to do this, but we could look into making it more customizable with css.  I'm not exactly sure how to best do that, but in general, I think the current approach could be more flexible.  Right now ALL of the CSS for hints is fixed in pixels.  One idea would be to change it to work with `font-size` and `em`, so someone could just adjust `.introjs-hint { font-size: 12pt }` for example and affect all instances of `em`.
