### ISSUE TITLE
Clicking outside tooltip closes it

### ISSUE THREAD

**Issue by prashantsingh0205** [usablica/intro.js#673]
When you click outside tooltip on the overlay portion, the toolltip disappears and the whole intro gets unfortunately dead in midway.

**Comment by afshinm** [comment]
please share your code/example.

**Comment by khushbun** [comment]
How can you close without resolving or a discussion on it ? and you can look at all your demos. Same thing happens. Why you need my code ? And if there is an option already for having a non cancel-able tooltip just comment it.

**Comment by prashantsingh0205** [comment]
How can you close without resolving or a discussion on it ? and you can look at all your demos. Same thing happens. Why you need my code ? And if there is an option already for having a non cancel-able tooltip just comment it.

**Comment by afshinm** [comment]
1. I closed the case because you didn't provide useful information to find or fix any issues.
2. What do you mean by "all your demos"? this demo works fine: http://introjs.com/example/hello-world/index.html
3. When you create an issue you should provide an example that helps to find the issue and solve it. You didn't so I asked for an example (not your code).

Hope that makes sense. Cheers.

**Comment by prashantsingh0205** [comment]
Hi,

PFA, a demo that depicts my issue.





[image: --]
Prashant Singh
[image: http://]about.me/prashantsingh0205
<http://about.me/prashantsingh0205>


On Wed, Dec 28, 2016 at 12:40 AM, Afshin Mehrabani <notifications@github.com

**Comment by bjines** [comment]
He is referring to the fact that 'exitOnOverlayClick' is defaulted to true and was not sure how to turn it off.
The fix is inside the documentation, but may not be considered 'obvious'.

Going to the options section of the documentation is where the fix is listed: http://introjs.com/docs/intro/options/

Using the 'setOptions' function is the way to resolve this: introJs().setOption("exitOnOverlayClick", false);
