### ISSUE TITLE
Missing tabindex on prev and next buttons ?

### ISSUE THREAD

**Issue by czelusniakdawid** [usablica/intro.js#731]
Hi!
I have just one short question. Why can I focus on through all bullets, skip and done buttons by pressing Tab key, but I can't do this through prev and next buttons ? Could you add tabindex to those in future release ?
Thanks in advance :)

**Comment by bozdoz** [comment]
Looks like this problem was introduced in #340, and I do not know why.  That PR claims to solve focus problems surrounding the ENTER key; however, it also removed `tabIndex` from both prev and next buttons, and conditionally applies `tabIndex = -1` which also makes it un-tabbable. 

I would recommend removing ALL of those lines:

https://github.com/usablica/intro.js/blob/55f6bb746a9f48e43d4cc6b8740e28f1c4dfedf4/intro.js#L1160-L1165

https://github.com/usablica/intro.js/blob/55f6bb746a9f48e43d4cc6b8740e28f1c4dfedf4/intro.js#L1189-L1191

https://github.com/usablica/intro.js/blob/55f6bb746a9f48e43d4cc6b8740e28f1c4dfedf4/intro.js#L1219-L1221

Unless there is some other reason for them being there.  It seems unrelated to the topic of the PR, and I can't see why it would be needed.  Thoughts, @afshinm ?

**Comment by czelusniakdawid** [comment]
Thank you for your answer.

**Comment by afshinm** [comment]
@bozdoz hmm, that's weird yeah. User should be able to navigate with tab between keys.

**Comment by bozdoz** [comment]
I stick to what I said above.  I think we should remove the lines that remove the tabindex's.  I don't understand why they'd be removed, also I think the PR that removed them didn't mention it, so I don't think it was obvious.  Perhaps it was one person's preference.
