### ISSUE TITLE
Tooltip content is not inserted when onafterchange() is triggered

### ISSUE THREAD

**Issue by phaust** [usablica/intro.js#759]
Hi!

When trying to work with text/elements inside of tooltips right after a step change occured, it's not possible to select any of them.

It seems, the whole tooltip content is inserted after `onafterchange` event is triggered.

I wrote a little [JSFiddle](https://jsfiddle.net/uyxs2n6m/13/) to demonstrate that I can't ouput a tooltip elements inner HTML in an `onafterchange` event listener.

In addition to a fix of this problem, I think it would be nice to have access not only to the element of the new step as an argument in the function callbacks, but to the tooltip element too.

By the way, thanks for the nice work on this library so far.

**Comment by metronomx** [comment]
document.getElementsByClassName('link') returns a node list, but not a single item

should be:
`var linkContent = document.getElementsByClassName('link')[0].innerHTML;`

**Comment by afshinm** [comment]
thanks @metronomx.

**Comment by phaust** [comment]
OK, thx for that. I updated the [Fiddle](https://jsfiddle.net/uyxs2n6m/16/).

I can't see how this fixes the issue. Did I miss something here? Why is this issue closed?

**Comment by aried3r** [comment]
@afshinm, even with that fix, the bug still persists in the updated JSFiddle.

**Comment by bozdoz** [comment]
I think the issue here is that the tooltip content is being created within a timeout:

https://github.com/usablica/intro.js/blob/master/intro.js#L982

Because of this, onafterchange triggers **before** the tooltip content has been changed.  I'm not really sure why the timeout exists (would have to look through the blames to find out).  One solution would be to call onafterchange in the timeout function.

**Comment by bozdoz** [comment]
Found it: https://github.com/usablica/intro.js/commit/724dc5d1936f4ed9e6d3deb718cf10745baa2764#diff-42068bed56449c4ec84ddf8745e56b7cR229

Timeout is for css transitions.  I think we would need to call `onafterchange` within the timeout then; obviously need to rework some of the logic so that it doesn't fire twice (because it's called at the end of the outer function too), and perhaps make sure it at least fires once (because the timeout is cleared)?
