### ISSUE TITLE
Disable Auto-Scrolling

### ISSUE THREAD

**Issue by bagzli** [usablica/intro.js#823]
Is it possible to completely disable auto scrolling feature of the introjs?

setOption("scrollToElement", false) is not working for me.

**Comment by bozdoz** [comment]
I think the library should disable scrolling.  But I am unsure if everyone else feels the same way.  Perhaps the library should auto-disable scrolling, and optionally allow for it.  Anyone else have thoughts on this?

**Comment by DanielSchuech** [comment]
I think there are two cases for scrolling which have to be divided:
1) auto scroll to the element of the step (issue creator)
2) general scrolling by a user when we started the tutorial (regarding your post #826)

The first case should be enabled by default in my opinion. I think its a very usefull feature for users when the page will be scrolled to the focused element.

I am going to post my opinion about 2) in #826 because i dont think that the issue is related to this

**Comment by bozdoz** [comment]
I suppose I misunderstood this Issue.  I can take a look into this bug.

**Comment by ibnYusrat** [comment]
Even when I completely remove the _scrollTo function from intro.js, it still scrolls to the element. I have no idea how it is doing it.

**Comment by MSafter** [comment]
@ibnYusrat I've managed to "disable" the scrolling with this workaround 
```
public scrollTop() {
        window.scrollTo(0, 0);
}
introJs().onafterchange(this.scrollTop.bind(this));
```

**Comment by namlq93** [comment]
@bozdoz `scrollToElement: false ` not working. How to work? Thank you

**Comment by nikhilchauhankrantitechservices** [comment]
Is this issue resolved. If yes please provide the solution

**Comment by JacobNicotra** [comment]
Is there a solution to this?
