### ISSUE TITLE
introJs().showHintDialog does not work

### ISSUE THREAD

**Issue by payamspot** [usablica/intro.js#870]
Below is my code.
When i focus on a specific input, i want the hint to be visible, but i get this error: "Uncaught TypeError: Cannot read property 'hint' of undefined" 

-----------

`
<script src="~/Scripts/intro.js"></script>
<link rel="stylesheet" href="~/Content/introjs.css" />
<script>
    $(document).ready(function(){
        introJs().showHints();
    });
</script>

<script>
    $(document).ready(function () {
        $('#desease-name').on('focus', function () {
            //$(".introjs-hint[data-step='0']").trigger("click");
            introJs().showHintDialog(0);
        });
    });
</script>
`

**Comment by cotufaloschiflones** [comment]
In my particular scenario, I'm adding the hints programmatically and this way as below should work. It is working for me at least. I must to say anyway that maybe this specific part is not documented properly or...maybe it is not necessary...If you realize the error, it's pretty obvious...the element with the hint attached is undefined in the precise moment you have added the hints so you should wait to the next render cycle in order to not be undefined, this can be done with a setTimeout

```
introJs().addHints()
introJs().hideHints()

setTimeout(() => {
  introJs().showHintDialog(0)
}, 0)
```

In my particular case, I don´t want to show the hints, only the tooltip. So I have added and then I hide them to wait then to the next render cycle and then you can call safely to `showHintDialog` method
