### ISSUE TITLE
The introjs-helperLayer element cover the Introduced element

### ISSUE THREAD

**Issue by switer** [usablica/intro.js#90]
When give element style `position: absolute` and `z-index`,the introJS's  `introjs-helperLayer` element has covered the Introduced element. 
![intro](https://f.cloud.github.com/assets/1167668/327581/d20621b6-9b7a-11e2-9449-6965a690b0e6.jpg)

**Comment by farzad-salimijazi** [comment]
We had same problem when I was using slight animation for specific div by removing animation effect problem solved.

**Comment by msantos142** [comment]
Hi, any news on this issue? Tried to solve by myself manipulating the .introjs-showElement class but as expected it's not an aswer. Thanks

**Comment by afshinm** [comment]
Can anyone create a jsfiddle for this?

**Comment by MarkHerhold** [comment]
@afshinm I would like to purchase a license, but this issue is causing me problems. I can temporarily grant you access to my project with setup instructions if you want to see the bug yourself.

![image](https://cloud.githubusercontent.com/assets/4934732/24833551/14f47b22-1c9a-11e7-9604-8dd94ab427eb.png)

**Comment by ropeladder** [comment]
@afshinm I'm having a similar issue with `position: fixed` elements (although it works ok with `position: absolute`. I put up an example here: https://jsfiddle.net/7on23oku/1/

**Comment by sarbjit399** [comment]
![ice_screenshot_20170509-003125](https://cloud.githubusercontent.com/assets/13548103/25820451/e5655904-344e-11e7-9a61-4a39271e4631.png)

@afshinm I have the similar issue. My dropdown is in position: absolute and with z-index value. But introjs-fixParent class removes the z-index value by adding z-index: auto !important; and because of that it hides behind the searchbox (you can see the searchbox at the top of the dropdown in screenshot) whic h has the position: relative;

this is what it looks like when there is no overlay.
![ice_screenshot_20170509-003825](https://cloud.githubusercontent.com/assets/13548103/25820717/dcc0cda0-344f-11e7-9771-8fc8aeba3d0b.png)

**Comment by saddy-smoky** [comment]
I had a similar problem. The parent block had a "perspective: 1000px". After removing this property, it all worked

**Comment by sdawson26** [comment]
I also had a similar problem (trying to highlight some features on a mobile-friendly sidebar). It turns out the property `will-change` used in a few areas of my sidebar was causing the problem. This fixed it: 
```
.introjs-fixParent * {
  will-change: inherit !important;
}
```

**Comment by molidort** [comment]
The problem occurs when the element is using css animations like fadeIn/Out.

**Comment by twigs67** [comment]
I'm using introJs on a collapsing sidemenu. Unfortunately, removing fixed position isn't available to me. However, I have verified that switching the position from fixed to relative/absolute does work. 
Is there another solution to this problem?

**Comment by conlaoch1** [comment]
i have the exact same issue.
it appears that only the element, from which the intro is triggered, is contained within position:fixed, this error occures.

**Comment by divChecker** [comment]
Hello,

I have the same issue. I tried some solutions mentioned here, but still can't fix it. The element with index:9999999 from intro js "introjs-showElement" class seems not to work.
