### ISSUE TITLE
Would it be possible to ask user some questions?

### ISSUE THREAD

**Issue by brundles** [usablica/intro.js#907]
## This is a feature question / enhancement

Would it be possible to ask user some questions?

Ie. let say that i would like the user to answer a question - could be a dropdown with some options (like if they are "1-2 users", "3-5 users" or "5+ users", or if they "Prefer coffee", "Prefer tea", "Dislikes coffee and tea", etc.

Any suggestions on how to achieve this? Perhaps using the HTML option?

Thanks for any input :-D

**Comment by ChristianKarlsson86** [comment]
This is probably way after you actually need it, but since the issue is still open...

You can add HTML in the data-intro, even an entire form. You could add a select or an input together with a button and use AJAX or something similar to retrieve the data asynchronously (without having to refresh the page) and call nextStep from there.
