### ISSUE TITLE
Licensing still needs to be clarified

### ISSUE THREAD

**Issue by fgblomqvist** [usablica/intro.js#923]
It's been several years now without clarification on the issues raised here:
https://github.com/usablica/intro.js/issues/574
and here:
https://stackoverflow.com/questions/36158360/intro-js-is-opensource-or-not
and here:
https://github.com/usablica/intro.js/issues/814

The way I interpret it, as a Software Engineer, it's voluntary to subscribe to a proprietary license if you want to use this commercially. Clearly I am not alone in interpreting it this way judged by the issues above. If you want companies to pay you should explicitly say so, rather than vaguely state that you should sorta kinda pay if you want.

**Comment by adamcoulombe** [comment]
Also, FYI, I bought a "commercial license", and received no such license or any proof of purchase. Just an email saying "we will contact you shortly". Beware.

**Comment by adamcoulombe** [comment]
Version 2.0 uses MIT license, so may need to roll back

**Comment by afshinm** [comment]
Hello,

Sorry if it's not clear yet but I have replied to multiple threads on SO and GitHub to clarify the license. IntroJs *is* open-source. The license is https://www.gnu.org/licenses/agpl-3.0.en.html. It is free to use if your project is open-source, otherwise you'd need a commercial license. Read more here https://github.com/usablica/intro.js/blob/master/license.md.

Thanks!
